{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "102bf863-3ce1-431f-8d70-bc5ac3eb23a0",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "\"When creating a custom exception in Python, it is recommended to inherit from the built-in `Exception` class or one of its subclasses. Here's an\\nexplanation of why we use the `Exception` class as the base class for custom exceptions:\\n\\n1. Standardization and Consistency: Inheriting from the `Exception` class allows your custom exception to follow the standard exception hierarchy in \\nPython. It ensures consistency with other built-in exception classes and makes it easier for developers to understand and handle your custom exception\\nin a familiar way.\\n\\n2. Exception Handling: By inheriting from the `Exception` class, your custom exception inherits the necessary properties and behaviors of exceptions,\\nsuch as the ability to be caught and handled using `try-except` blocks. It enables you to treat your custom exception in a similar way to other \\nexceptions in the language.\\n\\n3. Compatibility and Interoperability: Inheriting from the `Exception` class ensures compatibility and interoperability with existing exception \\nhandling mechanisms, libraries, and frameworks in Python. It allows your custom exception to be used seamlessly with other code that handles \\nexceptions using the `Exception` base class or its subclasses.\\n\\n4. Customization and Extension: Although you inherit from the `Exception` class, you have the flexibility to customize and extend your custom \\nexception as needed. You can add additional attributes, methods, and behaviors specific to your custom exception while still maintaining the \\nfundamental exception functionality inherited from the `Exception` class.\\n\\nOverall, using the `Exception` class as the base class for custom exceptions provides a standardized and consistent approach, enables proper \\nexception handling, ensures compatibility with existing code, and allows for customization and extension as required. It promotes good programming \\npractices and facilitates effective error handling in Python.\""
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#1\n",
    "'''When creating a custom exception in Python, it is recommended to inherit from the built-in `Exception` class or one of its subclasses. Here's an\n",
    "explanation of why we use the `Exception` class as the base class for custom exceptions:\n",
    "\n",
    "1. Standardization and Consistency: Inheriting from the `Exception` class allows your custom exception to follow the standard exception hierarchy in \n",
    "Python. It ensures consistency with other built-in exception classes and makes it easier for developers to understand and handle your custom exception\n",
    "in a familiar way.\n",
    "\n",
    "2. Exception Handling: By inheriting from the `Exception` class, your custom exception inherits the necessary properties and behaviors of exceptions,\n",
    "such as the ability to be caught and handled using `try-except` blocks. It enables you to treat your custom exception in a similar way to other \n",
    "exceptions in the language.\n",
    "\n",
    "3. Compatibility and Interoperability: Inheriting from the `Exception` class ensures compatibility and interoperability with existing exception \n",
    "handling mechanisms, libraries, and frameworks in Python. It allows your custom exception to be used seamlessly with other code that handles \n",
    "exceptions using the `Exception` base class or its subclasses.\n",
    "\n",
    "4. Customization and Extension: Although you inherit from the `Exception` class, you have the flexibility to customize and extend your custom \n",
    "exception as needed. You can add additional attributes, methods, and behaviors specific to your custom exception while still maintaining the \n",
    "fundamental exception functionality inherited from the `Exception` class.\n",
    "\n",
    "Overall, using the `Exception` class as the base class for custom exceptions provides a standardized and consistent approach, enables proper \n",
    "exception handling, ensures compatibility with existing code, and allows for customization and extension as required. It promotes good programming \n",
    "practices and facilitates effective error handling in Python.'''"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "26514abe-a380-452f-af0f-b2c3f1401da8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "BaseException\n",
      "    Exception\n",
      "        TypeError\n",
      "            FloatOperation\n",
      "            MultipartConversionError\n",
      "        StopAsyncIteration\n",
      "        StopIteration\n",
      "        ImportError\n",
      "            ModuleNotFoundError\n",
      "            ZipImportError\n",
      "        OSError\n",
      "            ConnectionError\n",
      "                BrokenPipeError\n",
      "                ConnectionAbortedError\n",
      "                ConnectionRefusedError\n",
      "                ConnectionResetError\n",
      "                    RemoteDisconnected\n",
      "            BlockingIOError\n",
      "            ChildProcessError\n",
      "            FileExistsError\n",
      "            FileNotFoundError\n",
      "            IsADirectoryError\n",
      "            NotADirectoryError\n",
      "            InterruptedError\n",
      "                InterruptedSystemCall\n",
      "            PermissionError\n",
      "            ProcessLookupError\n",
      "            TimeoutError\n",
      "            UnsupportedOperation\n",
      "            itimer_error\n",
      "            herror\n",
      "            gaierror\n",
      "            SSLError\n",
      "                SSLCertVerificationError\n",
      "                SSLZeroReturnError\n",
      "                SSLWantWriteError\n",
      "                SSLWantReadError\n",
      "                SSLSyscallError\n",
      "                SSLEOFError\n",
      "            Error\n",
      "                SameFileError\n",
      "            SpecialFileError\n",
      "            ExecError\n",
      "            ReadError\n",
      "            URLError\n",
      "                HTTPError\n",
      "                ContentTooShortError\n",
      "            BadGzipFile\n",
      "        EOFError\n",
      "            IncompleteReadError\n",
      "        RuntimeError\n",
      "            RecursionError\n",
      "            NotImplementedError\n",
      "                ZMQVersionError\n",
      "                StdinNotImplementedError\n",
      "            _DeadlockError\n",
      "            BrokenBarrierError\n",
      "            BrokenExecutor\n",
      "                BrokenThreadPool\n",
      "            SendfileNotAvailableError\n",
      "            ExtractionError\n",
      "            VariableError\n",
      "        NameError\n",
      "            UnboundLocalError\n",
      "        AttributeError\n",
      "            FrozenInstanceError\n",
      "        SyntaxError\n",
      "            IndentationError\n",
      "                TabError\n",
      "        LookupError\n",
      "            IndexError\n",
      "            KeyError\n",
      "                NoSuchKernel\n",
      "                UnknownBackend\n",
      "            CodecRegistryError\n",
      "        ValueError\n",
      "            UnicodeError\n",
      "                UnicodeEncodeError\n",
      "                UnicodeDecodeError\n",
      "                UnicodeTranslateError\n",
      "            UnsupportedOperation\n",
      "            JSONDecodeError\n",
      "            SSLCertVerificationError\n",
      "            Error\n",
      "            UnsupportedDigestmodError\n",
      "            IllegalMonthError\n",
      "            IllegalWeekdayError\n",
      "            ParserError\n",
      "            ClassNotFound\n",
      "            ClipboardEmpty\n",
      "            MessageDefect\n",
      "                NoBoundaryInMultipartDefect\n",
      "                StartBoundaryNotFoundDefect\n",
      "                CloseBoundaryNotFoundDefect\n",
      "                FirstHeaderLineIsContinuationDefect\n",
      "                MisplacedEnvelopeHeaderDefect\n",
      "                MissingHeaderBodySeparatorDefect\n",
      "                MultipartInvariantViolationDefect\n",
      "                InvalidMultipartContentTransferEncodingDefect\n",
      "                UndecodableBytesDefect\n",
      "                InvalidBase64PaddingDefect\n",
      "                InvalidBase64CharactersDefect\n",
      "                InvalidBase64LengthDefect\n",
      "                HeaderDefect\n",
      "                    InvalidHeaderDefect\n",
      "                    HeaderMissingRequiredValue\n",
      "                    NonPrintableDefect\n",
      "                    ObsoleteHeaderDefect\n",
      "                    NonASCIILocalPartDefect\n",
      "                    InvalidDateDefect\n",
      "            MacroToEdit\n",
      "            InvalidFileException\n",
      "            UnequalIterablesError\n",
      "            InvalidVersion\n",
      "            _InvalidELFFileHeader\n",
      "            InvalidWheelFilename\n",
      "            InvalidSdistFilename\n",
      "            InvalidSpecifier\n",
      "            InvalidMarker\n",
      "            UndefinedComparison\n",
      "            UndefinedEnvironmentName\n",
      "            InvalidRequirement\n",
      "                RequirementParseError\n",
      "            InvalidVersion\n",
      "        AssertionError\n",
      "        ArithmeticError\n",
      "            FloatingPointError\n",
      "            OverflowError\n",
      "            ZeroDivisionError\n",
      "                DivisionByZero\n",
      "                DivisionUndefined\n",
      "            DecimalException\n",
      "                Clamped\n",
      "                Rounded\n",
      "                    Underflow\n",
      "                    Overflow\n",
      "                Inexact\n",
      "                    Underflow\n",
      "                    Overflow\n",
      "                Subnormal\n",
      "                    Underflow\n",
      "                DivisionByZero\n",
      "                FloatOperation\n",
      "                InvalidOperation\n",
      "                    ConversionSyntax\n",
      "                    DivisionImpossible\n",
      "                    DivisionUndefined\n",
      "                    InvalidContext\n",
      "        SystemError\n",
      "            CodecRegistryError\n",
      "        ReferenceError\n",
      "        MemoryError\n",
      "        BufferError\n",
      "        Warning\n",
      "            UserWarning\n",
      "                GetPassWarning\n",
      "                FormatterWarning\n",
      "            EncodingWarning\n",
      "            DeprecationWarning\n",
      "                ProvisionalWarning\n",
      "            PendingDeprecationWarning\n",
      "            SyntaxWarning\n",
      "            RuntimeWarning\n",
      "                ProactorSelectorThreadWarning\n",
      "                UnknownTimezoneWarning\n",
      "                PEP440Warning\n",
      "            FutureWarning\n",
      "                ProvisionalCompleterWarning\n",
      "            ImportWarning\n",
      "            UnicodeWarning\n",
      "            BytesWarning\n",
      "            ResourceWarning\n",
      "            DeprecatedTzFormatWarning\n",
      "            PkgResourcesDeprecationWarning\n",
      "        _OptionError\n",
      "        _Error\n",
      "        error\n",
      "        Verbose\n",
      "        Error\n",
      "        SubprocessError\n",
      "            CalledProcessError\n",
      "            TimeoutExpired\n",
      "        TokenError\n",
      "        StopTokenizing\n",
      "        ClassFoundException\n",
      "        EndOfBlock\n",
      "        TraitError\n",
      "        Error\n",
      "        Error\n",
      "            CancelledError\n",
      "            TimeoutError\n",
      "            InvalidStateError\n",
      "        _GiveupOnSendfile\n",
      "        error\n",
      "        Incomplete\n",
      "        TimeoutError\n",
      "        InvalidStateError\n",
      "        LimitOverrunError\n",
      "        QueueEmpty\n",
      "        QueueFull\n",
      "        Empty\n",
      "        Full\n",
      "        ArgumentError\n",
      "        ZMQBaseError\n",
      "            ZMQError\n",
      "                ContextTerminated\n",
      "                Again\n",
      "                InterruptedSystemCall\n",
      "            ZMQBindError\n",
      "            NotDone\n",
      "        PickleError\n",
      "            PicklingError\n",
      "            UnpicklingError\n",
      "        _Stop\n",
      "        ArgumentError\n",
      "        ArgumentTypeError\n",
      "        ConfigError\n",
      "            ConfigLoaderError\n",
      "                ArgumentError\n",
      "            ConfigFileNotFound\n",
      "        ConfigurableError\n",
      "            MultipleInstanceError\n",
      "        ApplicationError\n",
      "        error\n",
      "        TimeoutError\n",
      "        error\n",
      "        ReturnValueIgnoredError\n",
      "        KeyReuseError\n",
      "        UnknownKeyError\n",
      "        LeakedCallbackError\n",
      "        BadYieldError\n",
      "        ReturnValueIgnoredError\n",
      "        Return\n",
      "        InvalidPortNumber\n",
      "        error\n",
      "        LZMAError\n",
      "        RegistryError\n",
      "        _GiveupOnFastCopy\n",
      "        Error\n",
      "            NoSectionError\n",
      "            DuplicateSectionError\n",
      "            DuplicateOptionError\n",
      "            NoOptionError\n",
      "            InterpolationError\n",
      "                InterpolationMissingOptionError\n",
      "                InterpolationSyntaxError\n",
      "                InterpolationDepthError\n",
      "            ParsingError\n",
      "                MissingSectionHeaderError\n",
      "        NoIPAddresses\n",
      "        BadZipFile\n",
      "        LargeZipFile\n",
      "        BadEntryPoint\n",
      "        NoSuchEntryPoint\n",
      "        DuplicateKernelError\n",
      "        ErrorDuringImport\n",
      "        NotOneValueFound\n",
      "        CannotEval\n",
      "        OptionError\n",
      "        BdbQuit\n",
      "        Restart\n",
      "        ExceptionPexpect\n",
      "            EOF\n",
      "            TIMEOUT\n",
      "        PtyProcessError\n",
      "        FindCmdError\n",
      "        HomeDirError\n",
      "        ProfileDirError\n",
      "        IPythonCoreError\n",
      "            TryNext\n",
      "            UsageError\n",
      "            StdinNotImplementedError\n",
      "        InputRejected\n",
      "        GetoptError\n",
      "        ErrorToken\n",
      "        PrefilterError\n",
      "        AliasError\n",
      "            InvalidAliasError\n",
      "        Error\n",
      "            InterfaceError\n",
      "            DatabaseError\n",
      "                InternalError\n",
      "                OperationalError\n",
      "                ProgrammingError\n",
      "                IntegrityError\n",
      "                DataError\n",
      "                NotSupportedError\n",
      "        Warning\n",
      "        SpaceInInput\n",
      "        DOMException\n",
      "            IndexSizeErr\n",
      "            DomstringSizeErr\n",
      "            HierarchyRequestErr\n",
      "            WrongDocumentErr\n",
      "            InvalidCharacterErr\n",
      "            NoDataAllowedErr\n",
      "            NoModificationAllowedErr\n",
      "            NotFoundErr\n",
      "            NotSupportedErr\n",
      "            InuseAttributeErr\n",
      "            InvalidStateErr\n",
      "            SyntaxErr\n",
      "            InvalidModificationErr\n",
      "            NamespaceErr\n",
      "            InvalidAccessErr\n",
      "            ValidationErr\n",
      "        ValidationError\n",
      "        EditReadOnlyBuffer\n",
      "        _Retry\n",
      "        InvalidLayoutError\n",
      "        HeightIsUnknownError\n",
      "        ParserSyntaxError\n",
      "        InternalParseError\n",
      "        _PositionUpdatingFinished\n",
      "        SimpleGetItemNotFound\n",
      "        UncaughtAttributeError\n",
      "        HasNoContext\n",
      "        ParamIssue\n",
      "        _JediError\n",
      "            InternalError\n",
      "            WrongVersion\n",
      "            RefactoringError\n",
      "        OnErrorLeaf\n",
      "        InvalidPythonEnvironment\n",
      "        MessageError\n",
      "            MessageParseError\n",
      "                HeaderParseError\n",
      "                BoundaryError\n",
      "            MultipartConversionError\n",
      "            CharsetError\n",
      "        Error\n",
      "        HTTPException\n",
      "            NotConnected\n",
      "            InvalidURL\n",
      "            UnknownProtocol\n",
      "            UnknownTransferEncoding\n",
      "            UnimplementedFileMode\n",
      "            IncompleteRead\n",
      "            ImproperConnectionState\n",
      "                CannotSendRequest\n",
      "                CannotSendHeader\n",
      "                ResponseNotReady\n",
      "            BadStatusLine\n",
      "                RemoteDisconnected\n",
      "            LineTooLong\n",
      "        InteractivelyDefined\n",
      "        KillEmbedded\n",
      "        Error\n",
      "            NoSuchProcess\n",
      "                ZombieProcess\n",
      "            AccessDenied\n",
      "            TimeoutExpired\n",
      "        _Ipv6UnsupportedError\n",
      "        QueueEmpty\n",
      "        QueueFull\n",
      "        DebuggerInitializationError\n",
      "        ExpatError\n",
      "        Error\n",
      "            ProtocolError\n",
      "            ResponseError\n",
      "            Fault\n",
      "        ParseBaseException\n",
      "            ParseException\n",
      "            ParseFatalException\n",
      "                ParseSyntaxException\n",
      "        RecursiveGrammarException\n",
      "        ResolutionError\n",
      "            VersionConflict\n",
      "                ContextualVersionConflict\n",
      "            DistributionNotFound\n",
      "            UnknownExtra\n",
      "        _Error\n",
      "        UnableToResolveVariableException\n",
      "        InvalidTypeInArgsException\n",
      "    GeneratorExit\n",
      "    SystemExit\n",
      "    KeyboardInterrupt\n",
      "    CancelledError\n",
      "    AbortThread\n"
     ]
    }
   ],
   "source": [
    "def print_exception_hierarchy(exception_class, indent=0):\n",
    "    print(' ' * indent + exception_class.__name__)\n",
    "    for subclass in exception_class.__subclasses__():\n",
    "        print_exception_hierarchy(subclass, indent + 4)\n",
    "\n",
    "\n",
    "# Print the Exception Hierarchy\n",
    "print_exception_hierarchy(BaseException)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "b0b21068-300f-45c8-bf79-0255b1f74291",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: division by zero\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "\"'In the above example, the code attempts to divide the number 10 by zero. Since division by zero is not allowed, it raises a ZeroDivisionError.\\nThe exception is caught in the except block, and the error message associated with the exception is printed.\""
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#3\n",
    "'''The ArithmeticError class in Python is the base class for exceptions that occur during arithmetic operations. It encompasses a range of specific \n",
    "arithmetic-related errors. Here are two common errors defined within the ArithmeticError class along with examples:\n",
    "\n",
    "ZeroDivisionError: This error occurs when you attempt to divide a number by zero.\n",
    "'''\n",
    "# Example 1: ZeroDivisionError\n",
    "try:\n",
    "    result = 10 / 0\n",
    "except ZeroDivisionError as e:\n",
    "    print(\"Error:\", e)\n",
    "''''In the above example, the code attempts to divide the number 10 by zero. Since division by zero is not allowed, it raises a ZeroDivisionError.\n",
    "The exception is caught in the except block, and the error message associated with the exception is printed.'''"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "1db40a29-f4dc-4648-abd5-987e328ca19d",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'In the above example, the code attempts to add 1 to an extremely large number. Since the resulting value exceeds the maximum representable value,\\nit raises an OverflowError. The exception is caught in the except block, and the associated error message is printed.'"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "'''OverflowError: This error occurs when a mathematical operation exceeds the maximum representable value.\n",
    "python\n",
    "Copy code\n",
    "# Example 2: OverflowError'''\n",
    "try:\n",
    "    result = 999999999999999999999999999999999999999999999999999999999999999999999999999 + 1\n",
    "except OverflowError as e:\n",
    "    print(\"Error:\", e)\n",
    "'''In the above example, the code attempts to add 1 to an extremely large number. Since the resulting value exceeds the maximum representable value,\n",
    "it raises an OverflowError. The exception is caught in the except block, and the associated error message is printed.'''"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "5c6b10d7-dc14-41d7-b8e7-fc46e63ab7ce",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error: 'd'\n"
     ]
    }
   ],
   "source": [
    "#4\n",
    "'''The `LookupError` class in Python is the base class for exceptions that occur when a lookup or indexing operation fails. It serves as a parent \n",
    "class for specific lookup-related exceptions, such as `KeyError` and `IndexError`. Here's an explanation of `LookupError` and two examples: `KeyError`\n",
    "and `IndexError`.\n",
    "\n",
    "1. `KeyError`: This error occurs when trying to access a dictionary or mapping with a key that does not exist.\n",
    "'''\n",
    "# Example 1: KeyError\n",
    "my_dict = {'a': 1, 'b': 2, 'c': 3}\n",
    "\n",
    "try:\n",
    "    value = my_dict['d']\n",
    "except KeyError as e:\n",
    "    print(\"Error:\",e)\n",
    "\n",
    "\n",
    "#In the above example, the code attempts to access the dictionary `my_dict` using the key `'d'`. Since the key `'d'` does not exist in the dictionary,\n",
    "#a `KeyError` is raised. The exception is caught in the `except` block, and the error message associated with the exception is printed.\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "fb894318-132c-49b3-9b30-1acf4bf05ac5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "list index out of range\n"
     ]
    }
   ],
   "source": [
    "#2.index error\n",
    "try:\n",
    "    l=[1,2,3,4]\n",
    "    print(l[6])\n",
    "except IndexError as e:\n",
    "    print(e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "30c601ea-9b6d-4244-aad0-bd9d0cd9b542",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ImportError: No module named 'non_existent_module'\n"
     ]
    }
   ],
   "source": [
    "#5\n",
    "'''`ImportError` is an exception class in Python that is raised when there is an error during the import of a module or when an imported module fails\n",
    "to satisfy some requirements.\n",
    "\n",
    "`ImportError` can occur in various scenarios, including:\n",
    "\n",
    "1. The module being imported is not found or cannot be located.\n",
    "2. The imported module has unresolved dependencies or requires additional modules that are not installed.\n",
    "3. There are syntax errors or other issues in the module being imported.\n",
    "\n",
    "`ModuleNotFoundError` is a subclass of `ImportError` that specifically indicates that the module being imported cannot be found. It was introduced \n",
    "in Python 3.6 as a more specific exception for import-related errors.\n",
    "\n",
    "Here's an example to illustrate the use of `ImportError` and `ModuleNotFoundError`:\n",
    "\n",
    "\n",
    "\n",
    "In the above code, an attempt is made to import a module named `non_existent_module`, which doesn't exist. When the import statement is encountered,\n",
    "it raises an `ImportError` or `ModuleNotFoundError`, depending on the Python version.\n",
    "\n",
    "If the module is not found, Python 3.6 and above will raise a `ModuleNotFoundError`, providing a more specific error message indicating the module\n",
    "that could not be found. In earlier versions of Python, it will raise a more generic `ImportError` with a message indicating the module name.\n",
    "\n",
    "By catching these exceptions, you can handle import-related errors in a controlled manner. This allows you to provide appropriate error handling,\n",
    "alternative import strategies, or informative error messages when importing modules in your Python code.\n",
    "'''\n",
    "try:\n",
    "    import non_existent_module\n",
    "except ImportError as e:\n",
    "    print(\"ImportError:\", e)\n",
    "except ModuleNotFoundError as e:\n",
    "    print(\"ModuleNotFoundError:\", e)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "24f02999-862a-4055-8276-6659b4484c57",
   "metadata": {},
   "outputs": [],
   "source": [
    "#6\n",
    "'''Certainly! Here are some best practices for exception handling in Python:\n",
    "\n",
    "1. Be specific in exception handling: Catch only the specific exceptions that you expect and can handle. Avoid using a generic `except` statement\n",
    "without specifying the exception type. This helps to catch and handle exceptions more precisely and avoids masking potential errors.\n",
    "\n",
    "2. Use multiple except blocks: If you need to handle different types of exceptions differently, use multiple `except` blocks, each handling a specific\n",
    "exception. This allows for specific error handling based on the type of exception raised.\n",
    "\n",
    "3. Use finally blocks for cleanup: When necessary, use `finally` blocks to ensure that cleanup code or resource release operations are executed,\n",
    "regardless of whether an exception occurred or not. The `finally` block is guaranteed to be executed, even if an exception is raised and caught.\n",
    "\n",
    "4. Avoid overly broad try-except blocks: It's generally not recommended to have a try-except block that encompasses a large portion of your code.\n",
    "Instead, keep the try-except block as small as possible, covering only the specific statements that might raise exceptions.\n",
    "\n",
    "5. Handle exceptions at the appropriate level: Handle exceptions at a level in your code where you have enough context and information to handle\n",
    "the exception effectively. Consider where the exception should be caught and handled to ensure proper error handling and maintain code readability.\n",
    "\n",
    "6. Provide informative error messages: When catching and handling exceptions, provide meaningful error messages that help in troubleshooting and \n",
    "understanding the cause of the exception. Include relevant information about the error context, variables, or conditions that led to the exception.\n",
    "\n",
    "7. Avoid silent failure: Avoid catching exceptions without taking any action or providing appropriate error handling. Silently ignoring exceptions \n",
    "can hide potential bugs or make it difficult to diagnose issues. Handle exceptions explicitly and consider appropriate actions, such as logging, error\n",
    "reporting, or fallback mechanisms.\n",
    "\n",
    "8. Use exception chaining: When catching an exception and re-raising it, use `raise ... from original_exception` syntax to preserve the original\n",
    "exception context. This allows for better understanding and debugging of the exception chain.\n",
    "\n",
    "9. Handle exceptions gracefully: Strive to handle exceptions gracefully, aiming for robust error handling that prevents program crashes and provides\n",
    "clear feedback to users. Graceful exception handling can help ensure the stability and reliability of your application.\n",
    "\n",
    "Remember that exception handling should be designed with the intent to handle exceptional conditions and recover from errors gracefully. It's important to strike a balance between catching and handling exceptions appropriately and allowing critical errors to propagate for proper diagnosis and troubleshooting.'''"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
